//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.225
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDFViewer.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UIStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIStrings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PDFViewer.Resources.UIStrings", typeof(UIStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The file is encrypted.
        /// </summary>
        internal static string ErrorFileEncrypted {
            get {
                return ResourceManager.GetString("ErrorFileEncrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The current export process will be cancelled. Continue?.
        /// </summary>
        internal static string InformationCurrentExportCancelled {
            get {
                return ResourceManager.GetString("InformationCurrentExportCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Export finished.
        /// </summary>
        internal static string MsgExportFinished {
            get {
                return ResourceManager.GetString("MsgExportFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exporting....
        /// </summary>
        internal static string StatusExporting {
            get {
                return ResourceManager.GetString("StatusExporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exporting page {0} of {1}....
        /// </summary>
        internal static string StatusExportingPage {
            get {
                return ResourceManager.GetString("StatusExportingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Powered by xPDF: {0} - {1}.
        /// </summary>
        internal static string StatusFormCaption {
            get {
                return ResourceManager.GetString("StatusFormCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Loading File....
        /// </summary>
        internal static string StatusLoadingFile {
            get {
                return ResourceManager.GetString("StatusLoadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Loading Page....
        /// </summary>
        internal static string StatusLoadingPage {
            get {
                return ResourceManager.GetString("StatusLoadingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Printing....
        /// </summary>
        internal static string StatusPrinting {
            get {
                return ResourceManager.GetString("StatusPrinting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ready.
        /// </summary>
        internal static string StatusReady {
            get {
                return ResourceManager.GetString("StatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resizing....
        /// </summary>
        internal static string StatusResizing {
            get {
                return ResourceManager.GetString("StatusResizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Searching bookmark....
        /// </summary>
        internal static string StatusSearchingBookmark {
            get {
                return ResourceManager.GetString("StatusSearchingBookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select SWFS directory.
        /// </summary>
        internal static string TitleSelectSWFSDirs {
            get {
                return ResourceManager.GetString("TitleSelectSWFSDirs", resourceCulture);
            }
        }
    }
}
